### ISSUE TITLE
SNI server

### ISSUE THREAD

**Issue by zeeshan-i-pathan** [tauplatform/tau#6]
Is there an issue in iOS when connecting to a server that allows only SNI. Getting SSLHandshake right after the call to CFWriteStreamWrite. The server has a valid cert when using SNI and self signed for No SNI. You can try connecting to badssl.com they have similar two cert configuration.

**Comment by zeeshan-i-pathan** [comment]
![image](https://cloud.githubusercontent.com/assets/6367539/21544729/a7be05d6-ce0c-11e6-9340-f1a3ef2c084b.png)
![image](https://cloud.githubusercontent.com/assets/6367539/21544730/a7be34e8-ce0c-11e6-8fcf-66885503174c.png)

**Comment by alex-epifanoff** [comment]
Can you please provide some details:
1) What tau platform/rhodes version are you using.
2) What is iOS version.
3) Samle code of your application.

FYI there is a RhoMobile community forum launched at forums.tau-technologies.com

**Comment by zeeshan-i-pathan** [comment]
I'm using the latest Rhodes Open source Version.
I tried connecting using iOS 9 and iOS 10.
Sample code for encountering this issue
result = Rho::AsyncHttp.post(:url=>url, :headers=>{"Content-type" => "application/json"},:body=>data,:ssl_verify_peer => true)
The connection is successful if i set :ssl_verify_peer => false but that does not solve the security Purpose as it skips validations for Certificate Chain.
